[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "docker compose up"

[environments.production]
[environments.production.postgres]
version = "13"

[environments.production.postgres.initScripts]
"01-schema.sql" = "https://raw.githubusercontent.com/DanYC1503/AuthenticApp/main/sql/01_schema.sql"